import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#0f0a1a'},
  header: {
    backgroundColor: '#4a1d6e',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  backButton: {marginBottom: 10},
  backText: {color: '#d4b8f0', fontSize: 13, fontWeight: '600'},
  codeBadge: {alignSelf: 'flex-start', backgroundColor: '#6b2fa015', borderWidth: 1, borderColor: '#6b2fa033', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3, marginBottom: 6, overflow: 'hidden'},
  codeBadgeText: {fontSize: 11, fontWeight: '700', color: '#8b45c5'},
  courseName: {fontSize: 18, fontWeight: '800', color: '#ffffff', marginBottom: 4, lineHeight: 24},
  courseMeta: {fontSize: 12, color: '#d4b8f0', marginBottom: 2},
  teacherRow: {flexDirection: 'row', alignItems: 'center', marginTop: 4, gap: 4},
  teacherLabel: {fontSize: 11, color: '#7a5fa0', fontWeight: '500'},
  teacherName: {fontSize: 11, color: '#f5a623', fontWeight: '700'},
  content: {flex: 1, padding: 14},
  sectionTitle: {fontSize: 16, fontWeight: '700', color: '#f1e6ff', marginBottom: 12, marginTop: 6},
  guideCard: {backgroundColor: '#1a0f2e', borderRadius: 14, padding: 14, marginBottom: 14, borderWidth: 1, borderColor: '#3d1f6e'},
  guideHeader: {marginBottom: 10, borderBottomWidth: 1, borderBottomColor: '#3d1f6e', paddingBottom: 10},
  guideTitle: {fontSize: 14, fontWeight: '700', color: '#f1e6ff', marginBottom: 4, lineHeight: 20},
  guideTeacherRow: {flexDirection: 'row', alignItems: 'center', gap: 4},
  guideTeacherLabel: {fontSize: 10, color: '#7a5fa0'},
  guideTeacherName: {fontSize: 10, color: '#f5a623', fontWeight: '600'},
  stepsTitle: {fontSize: 12, fontWeight: '700', color: '#b89fd4', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5},
  stepRow: {flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10, gap: 8},
  stepNumber: {width: 22, height: 22, borderRadius: 11, backgroundColor: '#6b2fa0', justifyContent: 'center', alignItems: 'center', marginTop: 1},
  stepNumberText: {fontSize: 10, fontWeight: '700', color: '#ffffff'},
  stepContent: {flex: 1},
  stepInstruction: {fontSize: 13, color: '#b89fd4', lineHeight: 19, marginBottom: 6},
  scriptBlock: {backgroundColor: '#0f0a1a', borderRadius: 8, borderWidth: 1, borderColor: '#3d1f6e', overflow: 'hidden'},
  scriptHeader: {backgroundColor: '#1a0f2e', paddingHorizontal: 10, paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: '#3d1f6e'},
  scriptHeaderText: {fontSize: 10, color: '#7a5fa0', fontWeight: '600'},
  scriptText: {fontFamily: 'monospace', fontSize: 11, color: '#7dd3fc', padding: 10, lineHeight: 18},
  exercisesSection: {marginTop: 12, backgroundColor: '#6b2fa011', borderRadius: 10, padding: 12, borderWidth: 1, borderColor: '#6b2fa033'},
  exercisesTitle: {fontSize: 12, fontWeight: '700', color: '#8b45c5', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5},
  exerciseRow: {flexDirection: 'row', alignItems: 'flex-start', marginBottom: 6, gap: 6},
  exerciseBullet: {fontSize: 11, color: '#f5a623', marginTop: 2, fontWeight: '700'},
  exerciseText: {flex: 1, fontSize: 12, color: '#b89fd4', lineHeight: 18},
  emptyContainer: {alignItems: 'center', paddingTop: 60},
  emptyText: {fontSize: 14, color: '#7a5fa0', textAlign: 'center'},
});