import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#0f0a1a'},
  header: {
    backgroundColor: '#4a1d6e',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  headerTop: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 2},
  headerTitle: {fontSize: 22, fontWeight: '800', color: '#ffffff', letterSpacing: -0.5},
  headerCount: {fontSize: 11, color: '#f5a623', fontWeight: '700', backgroundColor: '#f5a62320', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 20, overflow: 'hidden'},
  headerSubtitle: {fontSize: 12, color: '#d4b8f0'},
  listContent: {padding: 14, paddingBottom: 32},
  card: {backgroundColor: '#1a0f2e', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#3d1f6e', marginBottom: 10, elevation: 3},
  cardTop: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8},
  cardInfo: {flex: 1, marginRight: 8},
  courseBadge: {flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6},
  courseCode: {fontSize: 10, fontWeight: '700', color: '#8b45c5', backgroundColor: '#6b2fa015', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5, overflow: 'hidden', borderWidth: 1, borderColor: '#6b2fa033'},
  courseName: {fontSize: 10, color: '#7a5fa0', fontWeight: '500'},
  guideTitle: {fontSize: 14, fontWeight: '700', color: '#f1e6ff', lineHeight: 20, marginBottom: 4},
  teacherRow: {flexDirection: 'row', alignItems: 'center', gap: 4},
  teacherLabel: {fontSize: 10, color: '#7a5fa0'},
  teacherName: {fontSize: 10, color: '#f5a623', fontWeight: '600'},
  removeButton: {width: 34, height: 34, borderRadius: 17, backgroundColor: '#ef444420', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#ef444433'},
  removeButtonText: {fontSize: 14},
  cardFooter: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#3d1f6e', paddingTop: 8, marginTop: 2},
  stepsCount: {fontSize: 11, color: '#7a5fa0', fontWeight: '500'},
  openButton: {backgroundColor: '#6b2fa020', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, borderWidth: 1, borderColor: '#6b2fa033'},
  openButtonText: {fontSize: 11, color: '#8b45c5', fontWeight: '700'},
  emptyContainer: {alignItems: 'center', paddingTop: 80, paddingHorizontal: 30},
  emptyEmoji: {fontSize: 48, marginBottom: 14},
  emptyTitle: {fontSize: 17, fontWeight: '700', color: '#f1e6ff', marginBottom: 6, textAlign: 'center'},
  emptyText: {fontSize: 13, color: '#7a5fa0', textAlign: 'center', lineHeight: 20},
});