import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f0a1a',
  },
  header: {
    backgroundColor: '#4a1d6e',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    elevation: 10,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  headerBadge: {
    backgroundColor: '#8b45c5',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  headerBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 1,
  },
  headerSemester: {
    fontSize: 12,
    color: '#f5a623',
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#d4b8f0',
  },
  headerStats: {
    flexDirection: 'row',
    marginTop: 16,
    gap: 10,
  },
  statChip: {
    backgroundColor: '#ffffff15',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  statChipText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  listContent: {
    padding: 16,
  },
  card: {
    backgroundColor: '#1a0f2e',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3d1f6e',
    marginBottom: 12,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  courseCode: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8b45c5',
    backgroundColor: '#6b2fa015',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#6b2fa033',
  },
  credits: {
    fontSize: 12,
    fontWeight: '600',
    color: '#f5a623',
    backgroundColor: '#f5a62315',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
  },
  courseName: {
    fontSize: 17,
    fontWeight: '700',
    color: '#f1e6ff',
    marginBottom: 12,
    lineHeight: 23,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#3d1f6e',
    paddingTop: 10,
  },
  semesterText: {
    fontSize: 12,
    color: '#7a5fa0',
    fontWeight: '500',
  },
  arrow: {
    fontSize: 16,
    color: '#8b45c5',
    fontWeight: '700',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 80,
  },
  emptyEmoji: {
    fontSize: 48,
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#f1e6ff',
    marginBottom: 6,
  },
  emptySubText: {
    fontSize: 13,
    color: '#7a5fa0',
  },
});