import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#0f0a1a'},
  header: {
    backgroundColor: '#4a1d6e',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  headerTop: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8},
  headerBadge: {backgroundColor: '#8b45c5', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3},
  headerBadgeText: {fontSize: 10, fontWeight: '700', color: '#ffffff', letterSpacing: 1},
  headerSemester: {fontSize: 11, color: '#f5a623', fontWeight: '600'},
  headerTitle: {fontSize: 22, fontWeight: '800', color: '#ffffff', letterSpacing: -0.5, marginBottom: 2},
  headerSubtitle: {fontSize: 12, color: '#d4b8f0'},
  headerStats: {flexDirection: 'row', marginTop: 10, gap: 8},
  statChip: {backgroundColor: '#ffffff15', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4},
  statChipText: {fontSize: 11, color: '#ffffff', fontWeight: '600'},
  listContent: {padding: 14, paddingBottom: 32},
  card: {backgroundColor: '#1a0f2e', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#3d1f6e', marginBottom: 10, elevation: 3},
  cardHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8},
  courseCode: {fontSize: 11, fontWeight: '700', color: '#8b45c5', backgroundColor: '#6b2fa015', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, overflow: 'hidden', borderWidth: 1, borderColor: '#6b2fa033'},
  year: {fontSize: 11, fontWeight: '600', color: '#f5a623', backgroundColor: '#f5a62315', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, overflow: 'hidden'},
  courseName: {fontSize: 15, fontWeight: '700', color: '#f1e6ff', marginBottom: 10, lineHeight: 21},
  footer: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#3d1f6e', paddingTop: 8},
  semesterText: {fontSize: 11, color: '#7a5fa0', fontWeight: '500'},
  arrow: {fontSize: 15, color: '#8b45c5', fontWeight: '700'},
  emptyContainer: {alignItems: 'center', paddingTop: 80},
  emptyText: {fontSize: 16, fontWeight: '700', color: '#f1e6ff', marginBottom: 6},
  emptySubText: {fontSize: 13, color: '#7a5fa0'},
});