import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#0f0a1a'},
  header: {
    backgroundColor: '#4a1d6e',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  headerTitle: {fontSize: 22, fontWeight: '800', color: '#ffffff', marginBottom: 2, letterSpacing: -0.5},
  headerSubtitle: {fontSize: 12, color: '#d4b8f0', marginBottom: 12},
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff15',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#6b2fa033',
  },
  searchIcon: {fontSize: 14, marginRight: 8, color: '#b89fd4'},
  searchInput: {flex: 1, fontSize: 14, color: '#f1e6ff'},
  clearButton: {padding: 4},
  clearButtonText: {fontSize: 14, color: '#7a5fa0', fontWeight: '700'},
  resultsCount: {fontSize: 11, color: '#7a5fa0', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4, fontWeight: '500'},
  listContent: {padding: 14, paddingBottom: 32},
  card: {backgroundColor: '#1a0f2e', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#3d1f6e', marginBottom: 10, elevation: 3},
  cardHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8},
  courseCode: {fontSize: 11, fontWeight: '700', color: '#8b45c5', backgroundColor: '#6b2fa015', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, overflow: 'hidden', borderWidth: 1, borderColor: '#6b2fa033'},
  year: {fontSize: 11, fontWeight: '600', color: '#f5a623', backgroundColor: '#f5a62315', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, overflow: 'hidden'},
  courseName: {fontSize: 15, fontWeight: '700', color: '#f1e6ff', marginBottom: 6, lineHeight: 21},
  teacherRow: {flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 8},
  teacherLabel: {fontSize: 11, color: '#7a5fa0'},
  teacherName: {fontSize: 11, color: '#f5a623', fontWeight: '600'},
  footer: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#3d1f6e', paddingTop: 8},
  semesterText: {fontSize: 11, color: '#7a5fa0', fontWeight: '500'},
  arrow: {fontSize: 15, color: '#8b45c5', fontWeight: '700'},
  emptyContainer: {alignItems: 'center', paddingTop: 60},
  emptyEmoji: {fontSize: 44, marginBottom: 10},
  emptyText: {fontSize: 15, fontWeight: '700', color: '#f1e6ff', marginBottom: 4, textAlign: 'center'},
  emptySubText: {fontSize: 12, color: '#7a5fa0', textAlign: 'center'},
  initialContainer: {alignItems: 'center', paddingTop: 60, paddingHorizontal: 30},
  initialEmoji: {fontSize: 44, marginBottom: 10},
  initialText: {fontSize: 15, fontWeight: '700', color: '#f1e6ff', marginBottom: 4, textAlign: 'center'},
  initialSubText: {fontSize: 12, color: '#7a5fa0', textAlign: 'center', lineHeight: 20},
});